export const LOADING_DOCTORS = "LOADING_DOCTORS";
export const ERROR_DOCTORS = "ERROR_DOCTORS";
export const GET_DOCTORS = "GET_DOCTORS";
export const ADD_DOCTORS = "ADD_DOCTORS";
export const UPDATE_DOCTORS = "UPDATE_DOCTORS";
export const DELETE_DOCTORS = "DELETE_DOCTORS";